# This is a basic workflow to help you get started with Actions

name: Package-application-and-release

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  package:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      # Creates a release
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1.1.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
      - name: Package application
        uses: JackMcKew/pyinstaller-action-windows@main
        with:
          path: .
      - name: Upload release
        uses: actions/upload-release-asset@v1.0.2
        with:
          asset_name: File_Encryptor.exe
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: src/dist/windows
          asset_content_type: application/vnd.microsoft.portable-executable
